### ISSUE TITLE
Does not work with ruby 3.1.1

### ISSUE THREAD

**Issue by mrkamel** [DAddYE/leveldb#21]
It seems leveldb doesnt work with ruby 3.1.1

```
irb(main):001:0> RUBY_VERSION
=> "3.1.1"
irb(main):001:0> require "leveldb"
/usr/local/bundle/gems/fiddler-rb-0.1.2/lib/fiddler.rb:51:in `initialize': wrong number of arguments (given 5, expected 3..4) (ArgumentError)
	from /usr/local/bundle/gems/fiddler-rb-0.1.2/lib/fiddler.rb:51:in `new'
	from /usr/local/bundle/gems/fiddler-rb-0.1.2/lib/fiddler.rb:51:in `cdef'
	from /usr/local/bundle/gems/leveldb-0.1.9/lib/native.rb:12:in `<module:Native>'
	from /usr/local/bundle/gems/leveldb-0.1.9/lib/native.rb:4:in `<module:LevelDB>'
	from /usr/local/bundle/gems/leveldb-0.1.9/lib/native.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/leveldb-0.1.9/lib/leveldb.rb:1:in `<top (required)>'
```

running on alpine3.15 with leveldb-dev and snappy-dev installed

**Comment by bo-tato** [comment]
it's from the change in ruby3 in handling of keyword arguments, I made tiny change [here](https://github.com/DAddYE/fiddler/pull/2) and it's working
